development:
  adapter: async

test:
  adapter: async

# production:
#   adapter: redis
#   url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#   channel_prefix: ShownolaPortfolio_production

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: shownola-portfolio_production

  # FOR HEROKU REDISCLOUD:
  # production:
  #   adapter: redis
  #   url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://localhost:6379/1" } %>
  #   channel_prefix: shownola-portfolio_production
